### ISSUE TITLE
Request and one queation

### ISSUE THREAD

**Issue by Dan1jel** [Brutuski/tmux-crypto#1]
Would really like to get my native currency in bitcoins (SEK, Swedish Krona) and maybe an option to add how much bitcoin is worth, i do have a little but not 1 bitcoin. 

Would also know what's the refresh rate is, or if i can refresh every sec without exeeding the refresh limit. 

Thanks for this awesome tmux addon! 

Edit: didn't notice at first it update every sec. Thanks. Only SEK i would like to add (or other currently to be calculated automatically?) And if u could add your amount "0.00034btc in SEK"

**Comment by Brutuski** [comment]
> Would really like to get my native currency in bitcoins (SEK, Swedish Krona)

Ticker uses kraken's api to source all it's data. Kraken right now doesn't support SEK, so I would use another API to convert prices to SEK.
I will work on this and try to get it out in the next few days.

> And if u could add your amount "0.00034btc in SEK"

This I would work on after I get SEK support out first, just to keep things a bit more organized. Was planning on adding this feature soonish.

> Thanks for this awesome tmux addon!

Thanks a lot buddy, glad you find it useful. I plan to keep this updated and add some more helpful features and more currencies.

**Comment by Brutuski** [comment]
Updated the plugin, added new fiat currencies including _SEK_ as you wanted.

If you wouldn't mind, I would close this issue.

> if u could add your amount "0.00034btc in SEK"

Perhaps you could start a new issue for this request, will work on this next I think.

Cheers!

**Comment by Dan1jel** [comment]
Somehow i cat get `#{btc_kr}` to display... `#{btc_eur}` works but nothing from kr.

**Comment by Brutuski** [comment]
> didn't think of SEK and used KR instead

Yea I went with the official currency codes, might get too confusing when more currencies are added otherwise.

>but i do see kr in front of the amount, could you please put kr at the End of the amount because that's our (swedish) way of seeing it :)

It seems I was a bit too hasty in closing this issue.

I corrected it now.

Check it out and I will close this issue afterwards.

Cheers!

**Comment by Dan1jel** [comment]
Looks great! Thank you so much for updating it and adding these features.
